sudo: false

language: php

php:
  - 7.0
  - 7.1

before_script:
    - composer install -o

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/unit --configuration phpunit.xml --coverage-text

matrix:
  fast_finish: true
