sudo: false

# Operating System
os : linux
group: stable
dist: precise

# Script Language
language: php

# Php Tests version
php:
  - 7.0
  - 7.1

before_script:
    - composer install -o

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text

matrix:
  fast_finish: true
