sudo: false

# Operating System
os : linux
group: stable
dist: trusty

# Script Language
language: php

# Php Tests version
php:
  - 7.0
  - 7.1

services:
  - postgresql

addons:
  postgresql: "9.5"

test:
  adapter: postgresql
  database: recipicious

before_script:
  - psql -c 'create database recipicious;' -U postgres
  - psql -d recipicious -U postgres -f ./Database.pgsql
  - psql -c "ALTER USER "postgres" WITH PASSWORD 'posgtres';" -U postgres
  - composer install -o -vv

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text

matrix:
  fast_finish: true

after_success:
  - travis_retry php vendor/bin/coveralls -v --exclude-no-stmt
